"""empty message

Revision ID: 5353284a1c9a
Revises: 6f7f1b395f93
Create Date: 2023-10-29 13:18:36.397237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5353284a1c9a'
down_revision: Union[str, None] = '6f7f1b395f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_phrase', 'phrases', ['language_id', 'phrase_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_phrase', 'phrases', type_='unique')
    # ### end Alembic commands ###
